<div class="alert alert-block alert-info">
<center>ESTATÍSTICA APLICADA</center>
<center>PROJETO I</center>
<center>ALUNO: Demétrio de Luna Gurgel</center>
</div>

In [1]:
import pandas as pd
import numpy as np
import datetime as dt

<div class="alert alert-block alert-info">
Primeira tarefa:
</div>

A primeira etapa se dá por usar o zipfile para ler os arquivos compactados direto da url do site, na página de download da prf,
já que os dados são disponibilizados em formato zip, é necessário usar a biblioteca zipfile, para que não seja necessário seu download na memória interna.

In [2]:
dados2018 = pd.read_csv('https://arquivos.prf.gov.br/arquivos/index.php/s/MaC6cieXSFACNWT/download', encoding='latin1', compression ='zip', sep=';')
dados2019 = pd.read_csv('https://arquivos.prf.gov.br/arquivos/index.php/s/kRBUylqz6DyQznN/download', encoding='latin1', compression ='zip', sep=';')
dados2020 = pd.read_csv('https://arquivos.prf.gov.br/arquivos/index.php/s/jdDLrQIf33xXSCe/download', encoding='latin1', compression ='zip', sep=';')
dados2021 = pd.read_csv('https://arquivos.prf.gov.br/arquivos/index.php/s/n1T3lymvIdDOzzb/download', encoding='latin1', compression ='zip', sep=';')

In [3]:
# Visualização do ano de 2018
dados2018

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,99973.0,2018-01-01,segunda-feira,00:20:00,RJ,116.0,"303,5",RESENDE,Condutor Dormindo,Saída de leito carroçável,...,4,1,0,4,1,"-22,46937","-44,44705",SR-RJ,DEL5/7,UOP03/RJ
1,99976.0,2018-01-01,segunda-feira,00:40:00,SC,282.0,"0,4",FLORIANOPOLIS,Não guardar distância de segurança,Colisão traseira,...,2,1,0,2,2,"-27,59971687","-48,57565694",SR-SC,DEL8/1,UOP01/SC
2,99977.0,2018-01-01,segunda-feira,00:30:00,RJ,493.0,1,ITABORAI,Ultrapassagem Indevida,Colisão frontal,...,0,3,1,1,3,"-22,763901","-42,927532",SR-RJ,DEL5/4,UOP02/RJ
3,99981.0,2018-01-01,segunda-feira,01:15:00,RS,386.0,134,SARANDI,Ingestão de Álcool,Colisão transversal,...,0,2,0,0,2,"-27,953636","-52,916374",SR-RS,DEL9/14,UOP01/RS
4,99982.0,2018-01-01,segunda-feira,00:20:00,RS,293.0,"151,7",CANDIOTA,Falta de Atenção à Condução,Saída de leito carroçável,...,1,0,0,1,1,"-31,395214","-53,78391174",SR-RS,DEL9/11,UOP03/RS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69290,252256.0,2018-12-24,segunda-feira,09:15:00,PI,343.0,"263,1",CAMPO MAIOR,Agressão Externa,Colisão com objeto estático,...,0,1,0,0,1,"-4,819326","-42,158821",SR-PI,DEL17/1,UOP03/PI
69291,252652.0,2018-12-12,quarta-feira,07:00:00,BA,101.0,321,PRESIDENTE TANCREDO NEVES,Falta de Atenção à Condução,Saída de leito carroçável,...,0,0,0,1,1,"-13,44768518","-39,42066193",SR-BA,DEL10/5,UOP03/BA
69292,252801.0,2018-11-15,quinta-feira,10:48:00,SP,116.0,529,BARRA DO TURVO,Falta de Atenção à Condução,Colisão traseira,...,0,0,1,1,2,"-24,939211","-48,301248",SR-SP,DEL6/5,UOP03/SP
69293,253040.0,2018-11-23,sexta-feira,19:30:00,RS,472.0,"573,5",URUGUAIANA,Desobediência às normas de trânsito pelo condutor,Queda de ocupante de veículo,...,1,1,0,1,2,"-29,76355779","-57,05200195",SR-RS,DEL9/13,UOP01/RS
69294,253078.0,2018-10-01,segunda-feira,04:31:00,GO,40.0,9,LUZIANIA,Não guardar distância de segurança,Saída de leito carroçável,...,0,0,0,1,1,"-16,131158","-47,957739",SR-DF,UOP01/DF,NaN

In [4]:
# Visualização do ano de 2019
dados2019

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,182210.0,2019-01-01,terça-feira,01:30:00,SP,116.0,218,GUARULHOS,Falta de Atenção à Condução,Colisão com objeto estático,...,0,0,0,4,1,"-23,46052014","-46,48772478",SR-SP,DEL6/1,UOP01/SP
1,182211.0,2019-01-01,terça-feira,01:30:00,PR,373.0,"177,3",PONTA GROSSA,Falta de Atenção à Condução,Colisão traseira,...,0,0,0,1,1,"-25,05533957","-50,22776753",SR-PR,DEL7/3,UOP01/PR
2,182212.0,2019-01-01,terça-feira,00:45:00,SC,101.0,16,GARUVA,Animais na Pista,Colisão com objeto estático,...,0,0,0,1,1,"-26,1216","-48,8826",SR-SC,DEL8/3,UOP01/SC
3,182214.0,2019-01-01,terça-feira,00:00:00,CE,20.0,"429,5",FORTALEZA,Ingestão de Substâncias Psicoativas,Colisão com objeto estático,...,1,0,0,1,1,"-3,76999","-38,670063",SR-CE,DEL16/1,UOP02/CE
4,182215.0,2019-01-01,terça-feira,01:00:00,MG,381.0,327,NOVA ERA,Falta de Atenção à Condução,Colisão transversal,...,1,1,0,1,2,"-19,7609","-43,0306",SR-MG,DEL4/3,UOP01/MG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67441,266255.0,2019-10-07,segunda-feira,09:10:00,ES,101.0,"270,5",SERRA,Falta de Atenção à Condução,Tombamento,...,1,1,0,1,2,"-20,23107","-40,27387",SR-ES,DEL12/2,UOP01/ES
67442,266406.0,2019-11-25,segunda-feira,07:20:00,PR,116.0,125,FAZENDA RIO GRANDE,Falta de Atenção à Condução,Colisão lateral,...,0,1,1,1,2,"-25,59505","-49,31631",SR-PR,DEL7/1,UOP03/PR
67443,266434.0,2019-06-03,segunda-feira,19:00:00,CE,222.0,"1,4",CAUCAIA,Não guardar distância de segurança,Colisão traseira,...,1,1,0,1,2,"-3,736507","-38,65337",SR-CE,DEL16/1,UOP01/CE
67444,266573.0,2019-07-13,sábado,19:35:00,PR,373.0,425,CANDOI,Defeito Mecânico no Veículo,Saída de leito carroçável,...,1,0,0,1,1,"-25,7118","-52,18374",SR-PR,DEL7/3,UOP02/PR
67445,266627.0,2019-10-22,terça-feira,20:20:00,BA,324.0,608,SIMOES FILHO,Defeito na Via,Queda de ocupante de veículo,...,0,0,0,1,1,"-12,78156","-38,41656",SR-BA,DEL10/1,UOP01/BA

In [5]:
# Visualização do ano de 2020
dados2020

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,260031.0,2020-01-01,quarta-feira,01:00:00,TO,153.0,"678,1",GURUPI,Animais na Pista,Atropelamento de Animal,...,5,0,0,5,1,"-11,77460203","-49,10744996",SR-TO,UOP01/TO,NaN
1,260036.0,2020-01-01,quarta-feira,01:00:00,RJ,116.0,178,NOVA IGUACU,Falta de Atenção do Pedestre,Atropelamento de Pedestre,...,0,1,0,0,1,"-22,75223028","-43,4379103",SR-RJ,DEL5/1,UOP02/RJ
2,260037.0,2020-01-01,quarta-feira,01:52:00,SC,101.0,"206,9",SAO JOSE,Ingestão de Álcool,Colisão lateral,...,0,1,0,1,2,"-27,59193546","-48,61824557",SR-SC,DEL8/1,UOP01/SC
3,260038.0,2020-01-01,quarta-feira,01:15:00,RO,364.0,236,CACOAL,Velocidade Incompatível,Saída de leito carroçável,...,1,0,0,1,1,"-11,44624577","-61,43761218",SR-RO,DEL21/2,UOP02/RO
4,260039.0,2020-01-01,quarta-feira,01:30:00,PR,153.0,360,REBOUCAS,Ingestão de Álcool,Capotamento,...,4,0,0,6,1,"-25,67503796","-50,75089805",SR-PR,DEL7/3,UOP04/PR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63543,364615.0,2020-03-20,sexta-feira,09:00:00,RN,304.0,"171,8",ANGICOS,Falta de Atenção à Condução,Colisão traseira,...,1,2,0,2,4,"-5,68711053","-36,419458",SR-RN,UOP03,DEL01
63544,364810.0,2020-09-12,sábado,23:50:00,BA,116.0,"11,5",VITORIA DA CONQUISTA,Ingestão de Álcool,Colisão lateral,...,0,2,0,1,2,"-14,87308214","-40,87141514",SR-BA,UOP01,DEL08
63545,364817.0,2020-10-30,sexta-feira,10:30:00,BA,116.0,"14,3",VITORIA DA CONQUISTA,Falta de Atenção à Condução,Colisão lateral,...,0,2,0,2,2,"-14,89597653","-40,86098671",SR-BA,UOP01,DEL08
63546,364835.0,2020-09-20,domingo,23:00:00,BA,116.0,8,VITORIA DA CONQUISTA,Velocidade Incompatível,Queda de ocupante de veículo,...,0,0,0,1,1,"-14,84732305","-40,88634968",SR-BA,UOP01,DEL08
63547,364903.0,2020-10-31,sábado,02:10:00,BA,116.0,3,VITORIA DA CONQUISTA,Animais na Pista,Atropelamento de Animal,...,1,0,0,1,1,"-14,824848","-40,861311",SR-BA,UOP01,DEL08

In [6]:
# Visualização do ano de 2021:
dados2021

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,331693.0,2021-01-01,sexta-feira,00:02:00,SC,101.0,"314,9",LAGUNA,Ingestão de álcool pelo condutor,Colisão traseira,...,0,2,0,1,2,-28.430294,-48.849251,SR-SC,UOP01,DEL02
1,331694.0,2021-01-01,sexta-feira,00:15:00,PR,376.0,188,MARIALVA,Velocidade Incompatível,Colisão com objeto,...,0,0,0,2,1,-23.466349,-51.828080,SR-PR,UOP01,DEL09
2,331696.0,2021-01-01,sexta-feira,00:00:00,SP,116.0,"110,6",TAUBATE,Demais falhas mecânicas ou elétricas,Incêndio,...,0,1,0,0,1,-23.034126,-45.552700,SR-SP,UOP01,DEL06
3,331699.0,2021-01-01,sexta-feira,01:20:00,SC,101.0,111,NAVEGANTES,Manobra de mudança de faixa,Colisão lateral,...,0,1,0,2,2,-26.839557,-48.714181,SR-SC,UOP04,DEL04
4,331701.0,2021-01-01,sexta-feira,00:30:00,PE,101.0,"45,1",IGARASSU,Reação tardia ou ineficiente do condutor,Colisão traseira,...,1,1,0,1,2,-7.865213,-34.907152,SR-PE,UOP02,DEL01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64510,425426.0,2021-05-13,quinta-feira,03:15:00,MG,381.0,"775,3",CAMPANHA,Condutor deixou de manter distância do veículo...,Colisão traseira,...,0,2,0,2,2,-21.790183,-45.446659,SR-MG,UOP02,DEL16
64511,425436.0,2021-11-15,segunda-feira,23:00:00,PA,10.0,"248,4",AURORA DO PARA,Transitar na contramão,Colisão transversal,...,1,1,0,2,2,-2.267754,-47.563084,SR-PA,UOP01,DEL02
64512,428107.0,2021-09-21,terça-feira,01:10:00,MG,50.0,20,ARAGUARI,Condutor Dormindo,Colisão com objeto,...,2,1,0,7,1,-18.587210,-48.056456,SR-MG,UOP02,DEL15
64513,435016.0,2021-12-29,quarta-feira,13:40:00,AC,364.0,170,BUJARI,Pista esburacada,Queda de ocupante de veículo,...,1,0,0,1,1,-9.766854,-68.056811,SR-AC,UOP01,DEL01
64514,441173.0,2021-08-22,domingo,17:10:00,MT,364.0,498,JANGADA,Reação tardia ou ineficiente do condutor,Colisão traseira,...,0,1,0,1,2,-15.263832,-56.455487,SR-MT,UOP02,DEL01

In [7]:
# Visualização de forma concatenada:
concatena = pd.concat([dados2018, dados2019, dados2020, dados2021])
concatena

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,99973.0,2018-01-01,segunda-feira,00:20:00,RJ,116.0,"303,5",RESENDE,Condutor Dormindo,Saída de leito carroçável,...,4,1,0,4,1,"-22,46937","-44,44705",SR-RJ,DEL5/7,UOP03/RJ
1,99976.0,2018-01-01,segunda-feira,00:40:00,SC,282.0,"0,4",FLORIANOPOLIS,Não guardar distância de segurança,Colisão traseira,...,2,1,0,2,2,"-27,59971687","-48,57565694",SR-SC,DEL8/1,UOP01/SC
2,99977.0,2018-01-01,segunda-feira,00:30:00,RJ,493.0,1,ITABORAI,Ultrapassagem Indevida,Colisão frontal,...,0,3,1,1,3,"-22,763901","-42,927532",SR-RJ,DEL5/4,UOP02/RJ
3,99981.0,2018-01-01,segunda-feira,01:15:00,RS,386.0,134,SARANDI,Ingestão de Álcool,Colisão transversal,...,0,2,0,0,2,"-27,953636","-52,916374",SR-RS,DEL9/14,UOP01/RS
4,99982.0,2018-01-01,segunda-feira,00:20:00,RS,293.0,"151,7",CANDIOTA,Falta de Atenção à Condução,Saída de leito carroçável,...,1,0,0,1,1,"-31,395214","-53,78391174",SR-RS,DEL9/11,UOP03/RS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64510,425426.0,2021-05-13,quinta-feira,03:15:00,MG,381.0,"775,3",CAMPANHA,Condutor deixou de manter distância do veículo...,Colisão traseira,...,0,2,0,2,2,-21.790183,-45.446659,SR-MG,UOP02,DEL16
64511,425436.0,2021-11-15,segunda-feira,23:00:00,PA,10.0,"248,4",AURORA DO PARA,Transitar na contramão,Colisão transversal,...,1,1,0,2,2,-2.267754,-47.563084,SR-PA,UOP01,DEL02
64512,428107.0,2021-09-21,terça-feira,01:10:00,MG,50.0,20,ARAGUARI,Condutor Dormindo,Colisão com objeto,...,2,1,0,7,1,-18.58721,-48.056456,SR-MG,UOP02,DEL15
64513,435016.0,2021-12-29,quarta-feira,13:40:00,AC,364.0,170,BUJARI,Pista esburacada,Queda de ocupante de veículo,...,1,0,0,1,1,-9.766854,-68.056811,SR-AC,UOP01,DEL01
64514,441173.0,2021-08-22,domingo,17:10:00,MT,364.0,498,JANGADA,Reação tardia ou ineficiente do condutor,Colisão traseira,...,0,1,0,1,2,-15.263832,-56.455487,SR-MT,UOP02,DEL01

<div class="alert alert-block alert-info">
Segunda tarefa:
</div>

**(a) quantos acidentes ocorreram em cada ano?**

Para resolver essa questão, estarei utilizando o comando len em cada um dos dataframes dos 3 anos, o len é responsável por fazer a contagem da quantidade de argumentos.

In [8]:
print("Acidentes 2018: {}".format(len(dados2018)))
print("Acidentes 2019: {}".format(len(dados2019)))
print("Acidentes 2020: {}".format(len(dados2020)))
print("Acidentes 2021: {}".format(len(dados2021)))

Acidentes 2018: 69295
Acidentes 2019: 67446
Acidentes 2020: 63548
Acidentes 2021: 64515

**(b) quantas variáveis cada conjunto de dados registra?**

Considerando que cada coluna do Dataframe é uma variável, o comando len também pode ser usado, porém destinado a contar somente a quantidade de colunas.

In [9]:
print("Variáveis 2018: {}".format(len(dados2018.columns)))
print("Variáveis 2019: {}".format(len(dados2019.columns)))
print("Variáveis 2020: {}".format(len(dados2020.columns)))
print("Variáveis 2021: {}".format(len(dados2021.columns)))

Variáveis 2018: 30
Variáveis 2019: 30
Variáveis 2020: 30
Variáveis 2021: 30

**(c) quais as cinco cidades brasileiras onde mais ocorreram acidentes em rodovias federais?**

Para realizar essa questão, é preciso combinar os dados da coluna de municípios, utilizando uma função do pandas chamada de groupby, para que a partir disso criar um "contador" com a utilização do size, cuja função é calcular tamanhos de grupos, e utilizando o reset_index depois de descartar e filtrar as linhas, essa função é usada para redefinir o índice do Python DataFrame resultante.

In [10]:
print('As cidades que mais ocorreram acidentes durante o periodo de 2018 até 2021:')
dados_totais = concatena.groupby(['municipio']).size().reset_index(name = 'Acidentes')
dados_totais = dados_totais.sort_values(by = 'Acidentes', ascending=False)
resposta = dados_totais.head()
df_reset=resposta.reset_index()
df_reset

As cidades que mais ocorreram acidentes durante o periodo de 2018 até 2021:

   index  municipio  Acidentes
0    253   BRASILIA       3978
1    551   CURITIBA       3962
2   1680   SAO JOSE       3011
3    743  GUARULHOS       2781
4   1246    PALHOCA       2496

**(d) quantos acidentes com feridos graves aconteceram na Paraíba em 2019?**

Usando um método de filtragem simples, usa-se um len para contar a quatidade de argumentos.

In [11]:
paraiba_2019 = dados2019[(dados2019['uf'] == 'PB') & (dados2019.feridos_graves >= 1)]
print('A Paraiba teve {} acidentes graves em 2019'.format(len(paraiba_2019)))

A Paraiba teve 414 acidentes graves em 2019

<div class="alert alert-block alert-info">
Terceira tarefa:
    
Para cada indicação abaixo, construa um novo dataframe, salvando-o com a terminação .csv.
</div>

**(a) ranking de acidentes por estado para todos os anos (um só arquivo combinando a
informação dos três anos):**

Utilizando o Dataframe com os anos concatenados, se faz uma filtragem com a utilização do groupby, após essa etapa é feito uma ordenação para a criação do ranking, logo depois esse dataframe é salvo em csv.

In [12]:
print("Estados com mais acidentes nos anos de 2018 até 2021:")
estados = concatena.groupby(['uf']).size().reset_index(name='total')
rank = estados.sort_values(by='total', ascending=False )
rank.to_csv("Acidentes_uf.csv")
rank

Estados com mais acidentes nos anos de 2018 até 2021:

    uf  total
10  MG  34483
23  SC  32034
17  PR  30185
18  RJ  17982
22  RS  17754
25  SP  17236
4   BA  13793
8   GO  13233
15  PE  10566
7   ES  10543
12  MT   9101
5   CE   6505
11  MS   6147
20  RO   6067
14  PB   5993
19  RN   5527
16  PI   5057
9   MA   4631
6   DF   3978
13  PA   3884
1   AL   2528
24  SE   2255
26  TO   2205
0   AC   1044
21  RR    991
3   AP    626
2   AM    456

**(b) acidentes por dia da semana para todos os anos (um só arquivo combinando a infor-
mação dos três anos).**

Foi realizado as mesmas etapas da questão "a", mudando apenas de estados para dia da semana.

In [13]:
print("Acidentes por dia da semana:")
d_semana = concatena.groupby(['dia_semana']).size().reset_index(name='total')
rank2 = d_semana.sort_values(by = 'total', ascending = False)
rank2.to_csv("Acidentes_semana.csv")
rank2

Acidentes por dia da semana:

      dia_semana  total
5         sábado  43872
0        domingo  43816
4    sexta-feira  40945
3  segunda-feira  35712
2   quinta-feira  34471
1   quarta-feira  33347
6    terça-feira  32641

<div class="alert alert-block alert-info">
Quarta tarefa:
    
Com relação a ocorrência dos acidentes, responda:
</div>

**(a) qual a causa mais frequente e a mais rara de acidentes registrados nos três anos?**

Para o dado de causa mais frenquente, é usado assim como nas questões anteriores, o groupby para filtrar a coluna e sort para ordenação, já o mais raro, foi aproveitado o dataframe do mais frequente, apenas adicionando a função tail para que seja pego o último índice.

In [14]:
#Causa mais frequente
causa = concatena.groupby(['causa_acidente']).size().reset_index(name = 'total')
rank3 = causa.sort_values(by='total', ascending = False)
print("Causa mais frequnete:")
rank3.head(1)

Causa mais frequnete:

                 causa_acidente  total
37  Falta de Atenção à Condução  73231

In [15]:
#Causa mais rara
print("Causa mais rara:")
rank3.tail(1)

Causa mais rara:

           causa_acidente  total
76  Sinalização encoberta      3

**(b) qual a proporção de pessoas ilesas e de feridos graves por mês em cada um dos anos
considerados? (proporção = numero de ilesos ou feridos graves/ número total de
pessoas envolvidas no acidente**

As proporções de cada mês estão nos DataFrames a seguir, que estão divididos por ano. Para fazer esses dataframes, usei o datetime para converter a coluna "data_inversa" em uma data para o df, o loc para filtrar as colunas pretendidas, o depois foi usado o groupby da mesma forma das questões anteriores, somando os dados com a função .sum(), logo após dividindo as somas para realizar o cálculo de proporção. O round, logo no final, é usado para delimitar as casas decimais.

In [38]:
#2018
dados2018["mes"] = pd.to_datetime(dados2018["data_inversa"]).dt.month
mes_2018 = dados2018.loc[:,["mes", "pessoas", "ilesos", "feridos_graves"]]
soma = mes_2018.groupby(by="mes").sum()
prop_ilesos = (soma["ilesos"]/soma["pessoas"])
prop_feridos = (soma["feridos_graves"]/soma["pessoas"])
prop = pd.DataFrame(prop_ilesos).rename(columns={0:"proporção ilesos"}).round(2)
prop["proporção feridos graves"] = pd.DataFrame(prop_feridos).round(2)
prop

     proporção ilesos  proporção feridos graves
mes
1                0.51                      0.09
2                0.50                      0.09
3                0.48                      0.10
4                0.43                      0.11
5                0.42                      0.11
6                0.43                      0.12
7                0.44                      0.11
8                0.43                      0.11
9                0.42                      0.12
10               0.43                      0.11
11               0.43                      0.12
12               0.43                      0.11

In [39]:
#2019
dados2019["mes"] = pd.to_datetime(dados2019["data_inversa"]).dt.month
mes_2019 = dados2019.loc[:,["mes", "pessoas", "ilesos", "feridos_graves"]]
soma = mes_2019.groupby(by="mes").sum()
prop_ilesos = (soma["ilesos"]/soma["pessoas"])
prop_feridos = (soma["feridos_graves"]/soma["pessoas"])
prop = pd.DataFrame(prop_ilesos).rename(columns={0:"proporção ilesos"}).round(2)
prop["proporção feridos graves"] = pd.DataFrame(prop_feridos).round(2)
prop

     proporção ilesos  proporção feridos graves
mes
1                0.42                      0.11
2                0.42                      0.11
3                0.43                      0.11
4                0.42                      0.11
5                0.42                      0.12
6                0.42                      0.12
7                0.44                      0.12
8                0.41                      0.12
9                0.42                      0.11
10               0.42                      0.12
11               0.43                      0.11
12               0.42                      0.11

In [40]:
#2020
dados2020["mes"] = pd.to_datetime(dados2020["data_inversa"]).dt.month
mes_2020 = dados2020.loc[:,["mes", "pessoas", "ilesos", "feridos_graves"]]
soma = mes_2020.groupby(by="mes").sum()
prop_ilesos = (soma["ilesos"]/soma["pessoas"])
prop_feridos = (soma["feridos_graves"]/soma["pessoas"])
prop = pd.DataFrame(prop_ilesos).rename(columns={0:"proporção ilesos"}).round(2)
prop["proporção feridos graves"] = pd.DataFrame(prop_feridos).round(2)
prop

     proporção ilesos  proporção feridos graves
mes
1                0.42                      0.11
2                0.42                      0.11
3                0.40                      0.11
4                0.38                      0.12
5                0.40                      0.12
6                0.42                      0.12
7                0.42                      0.11
8                0.42                      0.12
9                0.42                      0.12
10               0.41                      0.12
11               0.41                      0.12
12               0.41                      0.12

In [41]:
#2021
dados2021["mes"] = pd.to_datetime(dados2021["data_inversa"]).dt.month
mes_2021 = dados2021.loc[:,["mes", "pessoas", "ilesos", "feridos_graves"]]
soma = mes_2021.groupby(by="mes").sum()
prop_ilesos = (soma["ilesos"]/soma["pessoas"])
prop_feridos = (soma["feridos_graves"]/soma["pessoas"])
prop = pd.DataFrame(prop_ilesos).rename(columns={0:"proporção ilesos"}).round(2)
prop["proporção feridos graves"] = pd.DataFrame(prop_feridos).round(2)
prop

     proporção ilesos  proporção feridos graves
mes
1                0.43                      0.11
2                0.41                      0.12
3                0.41                      0.11
4                0.41                      0.12
5                0.42                      0.12
6                0.43                      0.11
7                0.43                      0.11
8                0.42                      0.12
9                0.42                      0.12
10               0.41                      0.12
11               0.43                      0.12
12               0.42                      0.11

**(c) mostre, reorganizando o conjunto de dados, se a pandemia conseguiu diminuir ou não
a incidência de acidentes nas rodovias federais.**

Para a reorganização dos dados foram feitas copias usando a função .copy(), a partir das copias foi feita uma nova coluna com a função .assing(), após isso, foi concatenado tudo em um dataframe e usado o groupby para a filtragem e contagem de quantidade de acidentes em cada ano.

In [22]:
#2018
copia18 = dados2018.copy()
dados18 = copia18.assign(ano=2018)

#2019
copia19 = dados2019.copy()
dados19 = copia19.assign(ano=2019)

#2020
copia20 = dados2020.copy()
dados20 = copia20.assign(ano=2020)

#2021
copia21 = dados2021.copy()
dados21 = copia21.assign(ano=2021)

concatena_copia = pd.concat([dados18, dados19, dados20, dados21])
df = concatena_copia.groupby(['ano']).size().reset_index(name='acidentes')
df_concatenado = df.sort_values(by='acidentes', ascending=False)

df_concatenado

    ano  acidentes
0  2018      69295
1  2019      67446
3  2021      64515
2  2020      63548

Analisando o dataframe acima, é possível perceber que a pandemia de certa forma conseguiu diminuir a incidência de acidentes, considerando que a pandemia começou no ano de 2020, é justamente o ano que tem menos acidentes, em 2021 tivemos um pequeno aumento, mas ainda sim temos menos acidentes do que antes da pandemia.